name: charge_go
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.11.0
  qr_code_scanner: ^1.0.1
  auto_size_text: ^3.0.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.8
  flutter_spinkit: ^5.1.0
  file_picker: ^5.0.1
  flutter_secure_storage: ^5.1.0
  get: ^4.6.5
  font_awesome_flutter: ^10.1.0
  share_plus: ^4.0.10+1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
# flutter pub pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/Logo.png"
  image_path_android: "assets/images/Logo.png"
  image_path_ios: "assets/images/Logo.png"


# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/Logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
